## 1
name: Build

## Actions that will be executed when you push code currently none
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: 
jobs:
  build:
    #needs: [ unit_tests ] #
    runs-on: ubuntu-latest
    steps:
      # 1
      - name: Checkout code
        uses: actions/checkout@v2
      # 2
      - name: Generate Release APK
        run: ./gradlew assembleRelease
      # 3
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      # 4
      - uses: actions/upload-artifact@v1
        with:
          name: release.apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

      - name: Upload to slack step
        uses: MeilCli/slack-upload-file@v1
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channels: 'random'
          file_path: ${{steps.sign_app.outputs.signedReleaseFile}}
          file_name: 'lajmeShqip.apk'
          file_type: 'apk'
          initial_comment: 'post by slack-upload-file'
