## 1
name: Build

## Actions that will be executed when you push code currently none
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install tools
        run: sdkmanager tools platform-tools

      - name: Generate Release APK
        run: ./gradlew assembleRelease

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1

        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Rename signed APK
        run: mv ${{steps.sign_app.outputs.signedReleaseFile}} app/build/outputs/apk/release/comfyFlux.apk


      - uses: actions/upload-artifact@v1
        with:
          name: comfyFlux.apk
          path: app/build/outputs/apk/release/comfyFlux.apk


      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: "Release ${{ github.ref }}"
          draft: false
          prerelease: false

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/release/comfyFlux.apk
          asset_name: comfyFlux.apk
          asset_content_type: application/vnd.android.package-archive

      - uses: MeilCli/slack-upload-file@v4
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: 'C07GHA7D43F'
          file_path: app/build/outputs/apk/release/comfyFlux.apk
          initial_comment: 'posted by github actions'
          file_name: 'comfyFlex.apk'
          file_type: 'apk'
